name: Deploy Website

on:
  push:
    branches:
      - main # كل مرة تعمل push للـ main يشتغل

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Prepare files
        run: |
          mkdir build
          cp -r HTML/home/* build/   # ينسخ كل الملفات من HTML/home إلى build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
